name: Detect root CA
description: Detect unsafe root CA from production files

runs:
  using: composite
  steps:
    - name: 🔍 Check for CA in Docker based files
      shell: bash
      run: |
        echo "Searching for Docker files..."
        exists=$(find . -type f -iname '*docker*' -exec grep -qi 'https://netfree.link/dl/unix-ca.sh' {} \; -print)
        if [ "$exists" ]; then
          echo "Root CA found in [${exists}], failing..."
          exit 1
        else
          echo "No root CA detected"
        fi

    - name: 🔍 Check for trusted hosts
      shell: bash
      run: |
        exists=$(find . -type f -exec grep -qi 'trusted-host' {} \; -print)
        if [ "$exists" ]; then
          echo "Trusted hosts found in [${exists}], failing..."
          exit 1
        else
          echo "No trusted hosts detected"
        fi

    - name: 🔍 Check for export CA variables
      shell: bash
      run: |
        pattern='(?i)\b(NODE_EXTRA_CA_CERTS|REQUESTS_CA_BUNDLE|SSL_CERT_FILE)\b'
        if grep -irlE "$pattern" . > /dev/null; then
          echo "CA variables found in the following files:"
          grep -irlE "$pattern" .
          echo "Failing..."
          exit 1
        else
          echo "No CA variables detected"
        fi
